## Analytics-zoo Cluster Serving

model:
  # model path must be provided
  path: /home/qihong/intel-analytics/models/imagenet_1k/serving_val_openvino_res50
  # name, default is serving_stream, you need to specify if running multiple servings
  name:
  # whether to disable the batch inference of the model; default: false, meaning the model can use batch inference
  batch_disabled:
data:
  # default, localhost:6379
  src:
  # default, None
  filter:
params:
  # default, 4
  core_number:
  # default: model number will auto-adapt to core_number, do not set it if not sure about the behavior
  model_number:
  # default: OFF
  performance_mode:
flink:
  rest:
redis:
  # default, 4g
  maxmem:
  timeout: 5000
secure:
  # default: false
  secure_enabled:
  # default:
  secure_trust_store_path:
  # default:
  secure_struct_store_password:
  # default: false
  model_encrypted:
